### ISSUE TITLE
Statikus kódanalízis

### ISSUE THREAD

**Issue by Mysteryusy** [BME-MIT-IET/iet-hf-2023-grafadatbazis#11]
Issue a statikus kódanalízissel kapcsolatos PR-ek trackeléséhez, különböző toolok által észlelt hibák javításának megszervezéséhez.

❗ Ha valaki nekikezd egy adott problémakategóriának ami például a ["doc/sonarlint.md"](https://github.com/BME-MIT-IET/iet-hf-2023-grafadatbazis/blob/main/doc/sonarlint.md)-ben le van írva kérem jelezze itt hogy más ne álljon neki ugyanannak. ❗

**Comment by Mysteryusy** [comment]
Az alábbiaknak állok neki: The import is never used, Remove this unusued local variable és különböző kisebb törléseket igénylő hibák (Unnecessary @SuppressWarnings, Redundant Superinterface)

**Comment by Mysteryusy** [comment]
Következő iterációban a változó és függvényneveket fogom a platformkonvencióknak megfelelően átnevezni. Ezen kívül a Random újrahasználását, hiányzó @Override-ok pótlását, a Stringek/Boxed típusok összehasonlítását és kisebb más változtatásokat fogom javítani.

**Comment by mate-bak** [comment]
Az alkalmazásban lévő konstansokat érdemes szerintem egy helyre mozgatni, és ott együttesen kezelni őket, illetve valami funkció szerinti mappastruktúrát is érdemes lenne létrehozni src-n belül.

**Comment by mate-bak** [comment]
Nekiállok kijavítani a SonarCloud által jelzett jelenlegi hibákat.

**Comment by Mysteryusy** [comment]
A SonarCloud által jelzett [Security Hotspot](https://sonarcloud.io/project/security_hotspots?id=BME-MIT-IET_iet-hf-2023-grafadatbazis)-ok javítását megkezdtem. Ezen kívül az [Issue](https://sonarcloud.io/project/issues?resolved=false&severities=BLOCKER&id=BME-MIT-IET_iet-hf-2023-grafadatbazis) fülön jelzett Blocker-Critical-Major súlyosságúakból azokat amik nem foglalkoznak a kognitív komplexitással.

**Comment by mate-bak** [comment]
Néhány, SonarCloud által jelzett hiba javítása: [PR](https://github.com/BME-MIT-IET/iet-hf-2023-grafadatbazis/pull/15) 
Ezen kívül a main branchen resolveoltam néhány Security Hotspot hibát.

**Comment by Mysteryusy** [comment]
A SonarCloud által jelzett maradék hibák javításának nekikezdtem, ezek közé tartozik az összes maradék Issue/Code Smell-ből a Minor és Info kategóriájú.

**Comment by Mysteryusy** [comment]
Végső dokumentáció és Issue-t záró PR: https://github.com/BME-MIT-IET/iet-hf-2023-grafadatbazis/pull/27
