### ISSUE TITLE
BDD tesztek készítése

### ISSUE THREAD

**Issue by mate-bak** [BME-MIT-IET/iet-hf-2023-grafadatbazis#8]

**Comment by mate-bak** [comment]
Alap BDD teszteset Virológus osztályhoz, BDD tesztek futásának felvétele CI-ba: [PR](https://github.com/BME-MIT-IET/iet-hf-2023-grafadatbazis/pull/7)

**Comment by mate-bak** [comment]
A következő alap Cucumber feature-ökre gondoltam, hogy jó lenne őket valamilyen mélységig megcsinálni:
- Virologist moves 
- Virologist interacts
- Virologist uses item 
- Virologist uses Agent 
- Virologist crafts-ot kiegészíteni, hogy többféle ágenst, vakcinát lefedjen
Ezekkel egyrészt lefedjük, amit egy játékos csinálhat a játékban, illetve szerintem az esetek a függőségeikkel együtt a játék egyéb fontosabb objektumainak főbb funkcionalitását is teszteli. (Mezők, Eszközök, Ágensek, Vakcinák)
Ha van bárkinek egyéb ötlete ide írhatja.

**Comment by Mysteryusy** [comment]
Nekem ötletem/kérésem inkább csak az 'Actions'-el kapcsolatban van hogy sokat segítene az átláthatóságon ha egy ilyen kis külön fülbe kerülne a teszt output mint a "Build with Maven" van, vagy a buildnél valahogy eltűntetni a sok download outputot.

**Comment by mate-bak** [comment]
Elkezdtem a mozgással kapcsolatos teszteket csinálni.

**Comment by xDman2000** [comment]
A [https://github.com/BME-MIT-IET/iet-hf-2023-grafadatbazis/commit/424d97179ac9be3e1d94a14ff7600a4396a58c12](Commit)-ban elkészítettem a Virologist uses Agent esetet.

**Comment by xDman2000** [comment]
Elkészült a Virologist uses Gear teszt eset is [Commit](https://github.com/BME-MIT-IET/iet-hf-2023-grafadatbazis/commit/93cbed952f9036faa4deeb91fe7a8903e3bb7ac8)

**Comment by mate-bak** [comment]
Mozgással kapcsolatos Cucumber tesztek: [PR](https://github.com/BME-MIT-IET/iet-hf-2023-grafadatbazis/pull/21)

**Comment by xDman2000** [comment]
Virologist uses Gear teszt eset kibővítése: [PR](https://github.com/BME-MIT-IET/iet-hf-2023-grafadatbazis/pull/24)

**Comment by xDman2000** [comment]
Virologist Field Interact teszt eset elkészítése: [PR](https://github.com/BME-MIT-IET/iet-hf-2023-grafadatbazis/pull/28)
